### ISSUE TITLE
Breadcrumb

### ISSUE THREAD

**Issue by vbonhomme** [ShakePeers/shakepeers-mediawiki-skin#1]
dans le même ordre d'idée, si on pouvait réduire un peu les listes de pages utiles autour du nom (ex [ici](https://shakepeers.org/Sp%C3%A9cial:Contributions/Vincent_Bonhomme))

**Comment by Rudloff** [comment]
C'est mieux [comme ça](https://beta.shakepeers.org/Sp%C3%A9cial:Contributions/Vincent_Bonhomme) ?

**Comment by vbonhomme** [comment]
cool !
même un poil plus petit ce serait acceptable je pense !

2015-02-22 18:05 GMT+01:00 Pierre Rudloff notifications@github.com:

> C'est mieux comme ça
> https://beta.shakepeers.org/Sp%C3%A9cial:Contributions/Vincent_Bonhomme
> ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ShakePeers/shakepeers-mediawiki-skin/issues/1#issuecomment-75445233
> .

## 

vincentbonhomme.fr http://www.vincentbonhomme.fr

**Comment by Rudloff** [comment]
Le Common.css grossissait le texte en fait.
Regarde voir là.
