### ISSUE TITLE
Marked as unmaintained on MediaWiki

### ISSUE THREAD

**Issue by jdlrobson** [ShakePeers/shakepeers-mediawiki-skin#10]
I tried to install this skin today but hit a few problems with the current version of MediaWiki (1.35). As a result I've marked this as unmaintained on [mediawiki.org](https://www.mediawiki.org/wiki/Skin:ShakePeers)

Just letting you know in case this is not true, and you want to apply fixes and update the  status on the wiki page.

**Comment by Rudloff** [comment]
This skin is indeed not maintained anymore. I will archive the repository.
