### ISSUE TITLE
Soucis de formatage sur Liquid Thread

### ISSUE THREAD

**Issue by vbonhomme** [ShakePeers/shakepeers-mediawiki-skin#3]
C'est pas très grave et en plus je pense que c'est un peu relou : https://shakepeers.org/Brouillon_talk:De_la_forme_au_nombre

**Comment by Rudloff** [comment]
J'ai corrigé quelques soucis, dis-moi si tu vois d'autres problèmes.

**Comment by vbonhomme** [comment]
beau !!

2015-03-08 23:05 GMT+01:00 Pierre Rudloff notifications@github.com:

> J'ai corrigé quelques soucis, dis-moi si tu vois d'autres problèmes.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ShakePeers/shakepeers-mediawiki-skin/issues/3#issuecomment-77777482
> .

## 

vincentbonhomme.fr http://www.vincentbonhomme.fr
